### ISSUE TITLE
Calling api.SetDelay() as mentioned in readme panics

### ISSUE THREAD

**Issue by ahmetalpbalkan** [ChimeraCoder/anaconda#168]
If you do this:

> 
![image](https://cloud.githubusercontent.com/assets/159209/21168484/23a1d566-c169-11e6-99a2-daf01796db3f.png)

You get the panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11cd32]

goroutine 1 [running]:
panic(0x24a620, 0xc42000c0d0)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
github.com/ahmetalpbalkan/goodbye/vendor/github.com/ChimeraCoder/tokenbucket.(*Bucket).SetRate(0x0, 0x0)
	/Users/alp/workspace/gopath-goodbye/src/github.com/ahmetalpbalkan/goodbye/vendor/github.com/ChimeraCoder/tokenbucket/tokenbucket.go:41 +0x22
github.com/ahmetalpbalkan/goodbye/vendor/github.com/ChimeraCoder/anaconda.(*TwitterApi).SetDelay(0xc420012780, 0x0)
	/Users/alp/workspace/gopath-goodbye/src/github.com/ahmetalpbalkan/goodbye/vendor/github.com/ChimeraCoder/anaconda/twitter.go:156 +0x39
main.mkClient(0xc4200ca9e0, 0x15, 0xc420019020, 0x2b, 0xc420010700, 0x31, 0xc420019050, 0x2a, 0xc420019050, 0x2a, ...)
	/Users/alp/workspace/gopath-goodbye/src/github.com/ahmetalpbalkan/goodbye/main.go:89 +0xe4
main.main()
	/Users/alp/workspace/gopath-goodbye/src/github.com/ahmetalpbalkan/goodbye/main.go:36 +0x3ac
```

because `api.bucket` field is nil.

**Comment by migreva** [comment]
I had a similar issue, but I found a fix

It looks like you have to call [`api.EnableThrottling()` ](https://godoc.org/github.com/ChimeraCoder/anaconda#TwitterApi.EnableThrottling) first, then you're able to call `api.SetDelay()`. 

The [README section on throttling](https://github.com/ChimeraCoder/anaconda#throttling) notes that throttling is off by default, but it would be nice to have a nice one-liner that tells the user how to enable Throttling (and explain a little more about the `bufferSize` argument in the `EnableThrottling()` function call)

**Comment by alexellis** [comment]
+1, four years later I'm getting the same issue.
